apiVersion: v1
kind: Service
metadata:
  labels:
    tech.challenge.service: fiap-pos-tech-challenge-api
  name: fiap-pos-tech-challenge-api
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    tech.challenge.service: fiap-pos-tech-challenge-api
