version: '3.4'
volumes:
  sql_data: {}

services:
  fiap.pos.tech.challenge.api:
    image: ${DOCKER_REGISTRY-}fiappostechchallengeapi
    depends_on:
      - mssqltools
    build:
      context: .
      dockerfile: ../Src/Adapter/Driver/Api/Dockerfile
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U sa -P SqlServer2019! -Q 'SELECT NAME FROM SYS.DATABASES'"]
      interval: 1s
      retries: 20
    volumes:
      - sql_data:/var/opt/mssql
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./tech-challenge-mer.sql:/tmp/tech-challenge-mer.sql
      - ./init-database.sh:/tmp/init-database.sh
    command: /bin/bash ./tmp/init-database.sh  
