apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: sqlserver
  template:
    metadata:
      name: sqlserver
      labels:
        apps: sqlserver
    spec:
      containers:
        - name: sqlserver-container
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Developer
            - name: SA_PASSWORD
              value: SqlServer2019!
          image: mcr.microsoft.com/mssql/server:2019-latest          
          ports:
            - containerPort: 1433
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sql-data
      volumes:
        - name: sql-data
          persistentVolumeClaim:
            claimName: sql-data
