apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tech.challenge.service: sqlserver
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      tech.challenge.service: sqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tech.challenge.network/fiap-pos-techchallenge-gurpo-71-default: "true"
        tech.challenge.service: sqlserver
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Developer
            - name: SA_PASSWORD
              value: SqlServer2019!
          image: mcr.microsoft.com/mssql/server:2019-latest
          livenessProbe:
            exec:
              command:
                - /opt/mssql-tools/bin/sqlcmd
                - -Usa
                - -PSqlServer2019!
                - -Q
                - SELECT NAME FROM SYS.DATABASES
            failureThreshold: 20
            periodSeconds: 10
          name: sqlserver
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sql-data
      restartPolicy: Always
      volumes:
        - name: sql-data
          persistentVolumeClaim:
            claimName: sql-data
