apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    tech.challenge.service: mssqltools-claim1
  name: mssqltools-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
